### ISSUE TITLE
Does not show the amount of money

### ISSUE THREAD

**Issue by hzb** [AntoineFr/flarum-ext-money#10]
I like this extension, and I find a bug, but I don’t know if this is a bug. Please look at

![Screen Shot 2020-05-11 at 12 01 04](https://user-images.githubusercontent.com/535675/81523016-2343d880-937f-11ea-897f-092b1c3ce3ba.png)

I can see the `Money`, but I can see the amount, is it a bug?

**Comment by AntoineFr** [comment]
Hello, you must add a tag in the money name which will be replaced with the user’s money. 
`[money]€` will produce `42€` for example

**Comment by hzb** [comment]
@AntoineFr My mistake, thank you so much.
