### ISSUE TITLE
money sum value not displayed

### ISSUE THREAD

**Issue by glitchtime25** [AntoineFr/flarum-ext-money#30]
see screenshot's - thanks!
![grafik](https://user-images.githubusercontent.com/115500665/201476843-f4bc9840-16ae-4f82-b672-1718c9e17641.png)
![grafik](https://user-images.githubusercontent.com/115500665/201476852-7d4c3b33-f099-4c7d-9f2b-ba26ba017b93.png)

**Comment by AntoineFr** [comment]
Hello @glitchtime25,

You have to include the `[money]` tag in the money name field and it will be dynamically replaced with the user's money.
For example `[money] €` will render *1000 €*
