### ISSUE TITLE
Idea - further notation for whole, tenths, hundredths, and thousandths

### ISSUE THREAD

**Issue by jblayk** [AntoineFr/flarum-ext-money#43]
On my forum we're referring to the whole money unit as Platinum, the Tenths as Gold, the Hundredths as Silver, and the Thousandths as Copper. It's Dungeons and Dragons inspired 😊

We're getting by with the money just called Platinum and loving the plugin of course, but we would really appreciate it if there's any chance you could add separate identifiers for: 
the whole number rounded down no matter what - maybe [whole]
the 1st decimal place - maybe [tenths]
the 2nd decimal place - maybe [hundredths]
the 3rd decimal place - maybe [thousandths]

This would give people the freedom to have slightly more layered money systems such as the one I outlined in the begining of my post
Or even to divide their current money system by 10 or 100 to have something else that their money turns into once they have 10 or 100 of it. I'm not saying this should replace the [money] identifier obviously, I just think it would be a good option for those who want it.

Even if 0.001 showed up as 0 Platinum, 0 Gold, 0 Silver, 1 Copper that would be fine for us tbch, although upon release I'm guessing some users would rather have it be a comma separated list where it only shows non 0 values in any one instance and that would look cleaner to be fair.

**Comment by AntoineFr** [comment]
Hello @jblayk , thank you for your suggestion.
I think it's very specific to some communities, I try to keep this extension as generic as possible.
You can write your own extender to alter the original display which is located in https://github.com/AntoineFr/flarum-ext-money/blob/master/js/src/forum/index.js
